CREATE MATERIALIZED VIEW DM_MDS.MV_DELINQUENCY_ALL_AREA
   BUILD IMMEDIATE
   REFRESH ON DEMAND
   AS SELECT AA.REGION
      , AA.DIVISION
      , AA.STATE_FIPS
      , CC.YEAR
      --, CC.ONLY_QUARTER_DESC
      , CC.QUARTERINYEAR
      , CC.QUARTER_ID
      --, CC.QUARTER_DESC
      --, CC.GEO
      , CC.TOTAL_NUMBER_LOANS_SERVICED
      , CC.TOTAL_PAST_DUE
      , CC.OVER_30DAYS
      , CC.OVER_60DAYS
      , CC.OVER_90PLUSDAYS
      , CC.FORECLO_INVENTORY_END_QUARTER
      , CC.FORECLO_STARTED_DURING_QUARTER
      , CC.SERIOUSLY_DELINQUENT
      FROM (SELECT REGION
            , DIVISION
            , STATE_FIPS
            , AREA_NAME
            , CASE 
              WHEN DIVISION = 0 THEN SUBSTR(AREA_NAME, 1, INSTR(AREA_NAME, ' ')-1)
              WHEN DIVISION != 0 AND STATE_FIPS = 0 THEN SUBSTR(AREA_NAME, 1, LENGTH(AREA_NAME) - 9)
              ELSE AREA_NAME 
              END AS New_Area_Name
            FROM DM_MDS.REGION_DIVISION_STATE_FIPS) AA
      JOIN
      (SELECT GG.QUARTER_DESC ONLY_QUARTER_DESC
      , DD.*
      FROM DM_MDS.LK_QUARTER_OF_YEAR GG
      JOIN
      (SELECT EE.YEAR_ID YEAR
      , EE.QUARTER_IN_YEAR QUARTERINYEAR
      , FF.*
      FROM DM_MDS.LK_QUARTER EE
      JOIN
      (SELECT * FROM DM_MDS.F_DELINQUENCY_ALL_AREA) FF
      ON EE.QUARTER_ID = FF.QUARTER_ID) DD
      ON GG.QUARTER_ID = DD.QUARTERINYEAR) CC
      ON AA.New_Area_Name = CC.GEO
      WHERE STATE_FIPS != 0; 